# Tugas Kelompok Aproksimasi Eigenvalue

Metode Numerik Informatika'24 Kelompok-8:
- Muchammad Yuda Tri Ananda (24060124110142)
- Muhamad Kemal Faza (24060124120013)
- Muhammad Akmal Fazli (24060124130123)
- Muhammad Dimas Arya Putra (24060124130062)
- Muhammad Zaidaan Ardiansyah (24060124140200)





# Eigenvalue

Dalam aljabar linear, sebuah eigenvalue (sering dilambangkan dengan $λ$) dari sebuah matriks persegi A berukuran $n \times n$ adalah sebuah skalar sedemikian rupa sehingga terdapat vektor tak nol $v$ berukuran $n \times 1$ yang memenuhi persamaan:

$$
Av=λv
$$

Vektor $v$ yang memenuhi persamaan ini untuk suatu eigenvalue $λ$ disebut sebagai eigenvector yang bersesuaian dengan eigenvalue $λ$.

# Aproksimasi Eigenvalue

Dalam konteks metode numerik, aproksimasi eigenvalue merujuk pada teknik-teknik yang digunakan untuk mencari nilai perkiraan (aproksimasi) dari eigenvalue suatu matriks. Hal ini diperlukan karena dalam banyak kasus, terutama untuk matriks berukuran besar atau matriks dengan struktur yang kompleks, perhitungan eigenvalue secara analitik (menggunakan persamaan karakteristik) menjadi sangat sulit atau bahkan tidak mungkin dilakukan secara efisien.

Beberapa metode numerik yang umum digunakan untuk mengaproksimasi eigenvalue meliputi:

1.  Metode Pangkat (Power Iteration)
2.  Metode Householder's (Transformasi Householder)
3.  Metode QR Algorithm
4.  SVD (Singular Value Decomposition)

Berikut penjelasan lebih rincinya beserta implementasinya dalam kode bahasa Python.

## 1. Power method

Metode Power adalah teknik iteratif yang digunakan untuk menentukan nilai eigen dominan dari suatu matriks, yaitu nilai eigen dengan magnitudo terbesar. Algoritma dasarnya adalah dengan mengalikan matriks $A$ secara berulang-ulang dengan vektor tebakan awal. Vektor hasil akan cenderung konvergen ke eigenvector yang bersesuaian dengan eigenvalue dominan, dan rasio elemen-elemen vektor pada iterasi berurutan akan memberikan aproksimasi eigenvalue dominan.

Dengan sedikit memodifikasi metode, metode ini juga dapat digunakan untuk menentukan nilai eigen lainnya. Salah satu fitur yang berguna dari metode Power adalah metode ini tidak hanya menghasilkan nilai eigen, tetapi juga vektor eigen terkait. Faktanya, metode Power sering kali diterapkan untuk menemukan vektor eigen untuk nilai eigen yang ditentukan oleh cara lain.


* Kelebihan: Relatif sederhana dan efisien untuk menemukan eigenvalue dominan dan eigenvectornya.
* Kekurangan: Hanya memberikan satu eigenvalue (yang dominan) dan konvergensinya bisa lambat jika terdapat eigenvalue lain yang magnitudonya dekat dengan eigenvalue dominan.

In [1]:
def max_abs_vec(x):
    # find maximum of the variable x
    max_val = abs(x[0][0])
    for i in range(len(x)):
        if abs(x[i][0]) > max_val:
            max_val = abs(x[i][0])
    return max_val

def power_method(n, N, x, A, TOL):
    # Normalisasi awal x
    max_x = max_abs_vec(x)
    for i in range(n):
        x[i][0] = x[i][0] / max_x

    y = [[0] for _ in range(n)]
    k = 1
    while k <= N:
        # y = A * x
        for i in range(n):
            total = 0
            for j in range(n):
                total += A[i][j] * x[j][0]
            y[i][0] = total

        max_y = max_abs_vec(y)
        if max_y == 0:
            print("A memiliki eigenvalue 0, pilih vektor x lain.")
            return 0

        # Hitung error
        ERR = [[0] for _ in range(n)]
        for i in range(n):
            nilai_baru = y[i][0] / max_y
            galat = abs(nilai_baru - x[i][0])
            ERR[i][0] = galat

        # print(f"Eigenvalue ke-{k}: {max_y}, Galat: {galat}")

        # Update x
        for i in range(n):
            x[i][0] = y[i][0] / max_y

        # cek max ERR, kalo < TOL berhenti
        iter = 0
        if max_abs_vec(ERR) < TOL:
            break


        k += 1
    return max_y, x, k

# Input
n = int(input("input dimensi matriks n: "))
N = int(input("input jumlah iterasi N: "))
TOL = float(input("nilai toleransi: "))

# input matriks A
A = []
for i in range(n):
    baris = list(map(float, input(f"input nilai elemen baris ke-{i+1} (dipisah spasi): ").split()))
    A.append(baris)

# input vector x ukuran nx1
x = []
print("input vector x: ")
for i in range(n):
    elemen = float(input())

    x.append([elemen])

eigenvalue, eigenvector, iterasi = power_method(n, N, x, A, TOL)
print(f"Aproksimasi Eigenvalue = {eigenvalue}")
print(f"Aproksimasi Eigenvector:{eigenvector}")
print(f"konvergen pada iterasi : {iterasi}")


ValueError: could not convert string to float: ''

## 2. Metode Householder's (Transformasi Householder)

Transformasi Householder adalah teknik yang digunakan untuk mengubah matriks menjadi bentuk yang lebih sederhana, seperti bentuk tridiagonal atau Hessenberg. Bentuk-bentuk ini memudahkan perhitungan eigenvalue menggunakan metode lain, seperti metode QR. Transformasi Householder sendiri bukanlah metode langsung untuk mengaproksimasi eigenvalue, tetapi merupakan langkah penting dalam algoritma yang lebih canggih.


Berikut ini kode dan contoh transformasi Householder.

In [ ]:
#Bentuk Tridiagonal
import sympy as sp
from sympy import Matrix, sympify

'''
N = int(input("Masukkan ordo matriks (N x N): "))
matriks = []

for i in range(N):
    baris = []
    for j in range(N):
        nilai_str = input(f"Masukkan elemen [{i}][{j}]: ")  # misalnya 1/2, 3, sqrt(2)
        nilai = sympify(nilai_str)  # ubah ke bentuk sympy
        baris.append(nilai)
    matriks.append(baris)

A = Matrix(matriks)

'''
#Langsung input matriks
A = Matrix([
    [4, 1, -2, 2],
    [1, 2, 0, 1],
    [-2, 0, 3, -2],
    [2, 1, -2, -1]
])

print("Matriks A:")
sp.pprint(A)

def householder_tridiagonal_rational(A):
    A = sp.Matrix(A)
    n = A.shape[0]

    for k in range(n - 2):
        x = A[k+1:, k]

        # Hitung alpha secara simbolik
        alpha = -sp.sign(x[0]) * sp.sqrt(sum(x[i]**2 for i in range(len(x))))

        # Hitung r
        r = sp.sqrt(sp.Rational(1, 2) * (alpha**2 - alpha * x[0]))

        # Buat vektor w (vektor kolom n x 1)
        w = sp.zeros(n, 1)
        w[k+1] = (x[0] - alpha) / (2 * r)
        for i in range(1, len(x)):
            w[k+1+i] = x[i] / (2 * r)

        # Matriks Householder
        P = sp.eye(n) - 2 * w * w.T

        # Update A
        A = (P * A * P).applyfunc(sp.simplify)

    return A

A_tri = householder_tridiagonal_rational(A)
print("Matriks A dalam bentuk tridiagonal:")
sp.pprint(A_tri)  # Tampilkan dalam bentuk pecahan


Matriks A:
⎡4   1  -2  2 ⎤
⎢             ⎥
⎢1   2  0   1 ⎥
⎢             ⎥
⎢-2  0  3   -2⎥
⎢             ⎥
⎣2   1  -2  -1⎦
Matriks A dalam bentuk tridiagonal:
⎡4    -3    0     0 ⎤
⎢                   ⎥
⎢-3  10/3  -5/3   0 ⎥
⎢                   ⎥
⎢          -33   68 ⎥
⎢0   -5/3  ────  ── ⎥
⎢           25   75 ⎥
⎢                   ⎥
⎢           68   149⎥
⎢0    0     ──   ───⎥
⎣           75   75 ⎦


Kemudian di bawah ini adalah kode penggunaan transformasi Householder ini dalam menemukan eigenvalue.

In [ ]:
#Bentuk Hessenberg
import numpy as np
from fractions import Fraction
from math import copysign, sqrt

def input_matrix():
    n = int(input("Masukkan ukuran matriks persegi n × n: "))
    A = [[Fraction(input(f"Masukkan elemen A[{i+1}][{j+1}]: ")) for j in range(n)] for i in range(n)]
    return np.array(A, dtype=object)

def householder_hessenberg_exact(A):
    n = A.shape[0]
    A_k = A.copy()

    for k in range(n - 2):
        # Ambil kolom ke-k dari baris k+1 ke bawah
        x = np.array([A_k[j, k] for j in range(k+1, n)], dtype=object)

        # Hitung alpha
        sum_squares = sum(x[j]**2 for j in range(len(x)))
        alpha = -copysign(Fraction(1), x[0]) * Fraction(sqrt(sum_squares))

        # Hitung r
        r = sqrt(Fraction(1, 2) * alpha**2 - Fraction(1, 2) * alpha * x[0])

        # Bentuk vektor w^(k)
        w = np.zeros(n, dtype=object)
        w[k+1] = (x[0] - alpha) / (2 * r)
        for j in range(k+2, n):
            w[j] = A_k[j, k] / (2 * r)

        # Matriks Householder P^(k)
        w = w.reshape((n, 1))
        P_k = np.identity(n, dtype=object) - 2 * (w @ w.T)

        # Update A^(k+1) = P A P
        A_k = P_k @ A_k @ P_k

    return A_k

# Jalankan program
print("=== Transformasi Householder ke bentuk Upper Hessenberg ===")
A_input = input_matrix()
Hessenberg = householder_hessenberg_exact(A_input)

print("\nBentuk Hessenberg:")
for row in Hessenberg:
    print([str(val) for val in row])


=== Transformasi Householder ke bentuk Upper Hessenberg ===
Masukkan ukuran matriks persegi n × n: 4
Masukkan elemen A[1][1]: 69
Masukkan elemen A[1][2]: 42
Masukkan elemen A[1][3]: 12
Masukkan elemen A[1][4]: 11
Masukkan elemen A[2][1]: 1
Masukkan elemen A[2][2]: 2
Masukkan elemen A[2][3]: 3
Masukkan elemen A[2][4]: 4
Masukkan elemen A[3][1]: 5
Masukkan elemen A[3][2]: 6
Masukkan elemen A[3][3]: 7
Masukkan elemen A[3][4]: 8
Masukkan elemen A[4][1]: 9
Masukkan elemen A[4][2]: 10
Masukkan elemen A[4][3]: 1
Masukkan elemen A[4][4]: 12

Bentuk Hessenberg:
['69.0', '-19.431403429817834', '-31.481554138749228', '-25.69693191329783']
['-10.344080432788598', '16.1214953271028', '4.78345937978824', '9.637883687634956']
['1.561501486795667e-15', '5.20371951871134', '3.0461304050985727', '-2.3734225231796895']
['9.562279821905554e-16', '6.661338147750939e-16', '-1.406686034134026', '1.8323742677986186']


## 3. Metode QR Algorithm

Metode QR adalah algoritma iteratif yang digunakan untuk menghitung semua eigenvalue dari matriks persegi $A$. Ide dasarnya adalah dengan faktorisasi matriks $Q$ (matriks ortogonal) dan $R$ (matriks segitiga atas) kemudian mengalikan $QR$ dalam urutan terbalik untuk mendapatkan matriks baru $A_1$.

$$
A_k = Q_kR_k
$$

$$
A_{k+1} = R_kQ_k
$$

Proses ini diulang, hingga menghasilkan matriks konfergen bentuk segitiga atas (untuk matriks real) atau bentuk blok segitiga atas (untuk matriks kompleks). Nilai-nilai pada diagonal matriks hasil konvergensi ini adalah aproksimasi dari eigenvalue matriks $A$ yang artinya akan dihasilkan $n$ buah eigenvalue.

- Kelebihan: Dapat menemukan semua eigenvalue secara relatif stabil dan efisien.
- Kekurangan: Lebih kompleks untuk diimplementasikan dibandingkan metode pangkat.

In [ ]:
import numpy as np
from scipy.linalg import qr

def householder_reduce_hessenberg(A):
    # Reduksi matriks A menjadi bentuk Hessenberg menggunakan transformasi Householder
    n = A.shape[0]
    H = np.copy(A)
    Q = np.identity(n)

    for k in range(n - 2):
        x = H[k + 1:, k]
        alpha = -np.sign(x[0]) * np.linalg.norm(x)
        e = np.zeros_like(x)
        e[0] = 1
        u = x - alpha * e
        v = u / (np.linalg.norm(u) + 1e-8)  # Tambahkan epsilon untuk menghindari division by zero

        H_k = np.identity(n)
        H_k[k + 1:, k + 1:] -= 2 * np.outer(v, v)

        H = H_k @ H @ H_k
        Q = Q @ H_k

    return H, Q

def qr_algorithm(A, iterations, tolerance):
    # Implementasi algoritma QR untuk mencari eigenvalue dari matriks A.
    n = A.shape[0]
    Ak, _ = householder_reduce_hessenberg(np.copy(A))
    print("Matriks setelah reduksi ke bentuk Hessenberg:")
    print(Ak)
    print("-" * 30)

    for i in range(iterations):
        print(f"Iterasi ke-{i+1}:")
        Q, R = qr(Ak)
        print("Q:")
        print(Q)
        print("R:")
        print(R)
        Ak_next = R @ Q
        print("Ak+1:")
        print(Ak_next)
        print("-" * 30)

        off_diagonal_sum = np.sum(np.abs(np.tril(Ak_next, -1)))
        Ak = Ak_next

        if off_diagonal_sum < tolerance:
            print(f"Konvergensi tercapai pada iterasi ke-{i+1}.")
            break

    eigenvalues = np.diag(Ak)
    return eigenvalues

if __name__ == "__main__":
  # Input
    n = int(input("input dimensi matriks n: "))
    I = int(input("input jumlah iterasi: "))
    E = float(input("nilai toleransi: "))

    # input matriks A
    A_list = []
    for i in range(n):
        baris = list(map(float, input(f"input nilai elemen baris ke-{i+1}: ").split()))
        A_list.append(baris)
    A = np.array(A_list)

    print("Memproses matriks A:")
    eigenvalues_A = qr_algorithm(A, iterations=I, tolerance=E)
    print("\nEigenvalues dari A:")
    print(eigenvalues_A)

input dimensi matriks n: 3
input jumlah iterasi: 25
nilai toleransi: 0.0001
input nilai elemen baris ke-1: 2 1 1
input nilai elemen baris ke-2: 1 2 1
input nilai elemen baris ke-3: 1 1 2
Memproses matriks A:
Matriks setelah reduksi ke bentuk Hessenberg:
[[ 2.00000000e+00 -1.41421354e+00  7.65366870e-09]
 [-1.41421354e+00  2.99999992e+00 -2.16478440e-08]
 [ 7.65366870e-09 -2.16478441e-08  9.99999996e-01]]
------------------------------
Iterasi ke-1:
Q:
[[-8.16496584e-01 -5.77350264e-01  1.91341725e-09]
 [ 5.77350264e-01 -8.16496584e-01  8.11794177e-09]
 [-3.12459718e-09  7.73298369e-09  1.00000000e+00]]
R:
[[-2.44948973e+00  2.88675128e+00 -2.18721799e-08]
 [ 0.00000000e+00 -1.63299313e+00  2.09895267e-08]
 [ 0.00000000e+00  0.00000000e+00  9.99999996e-01]]
Ak+1:
[[ 3.66666661e+00 -9.42809013e-01 -3.12459708e-09]
 [-9.42809013e-01  1.33333331e+00  7.73298354e-09]
 [-3.12459716e-09  7.73298365e-09  9.99999996e-01]]
------------------------------
Iterasi ke-2:
Q:
[[-9.68495998e-01 -2.4902

## 4. SVD (Singular Value Decomposition)

SVD adalah faktorisasi matriks menjadi tiga matriks: $A = U \Sigma V^T$, di mana $\Sigma$ adalah matriks diagonal dengan nilai singular non-negatif pada diagonalnya. **Secara langsung, SVD tidak memberikan eigenvalue.** Namun, jika matriks $A$ adalah matriks simetris positif-definit, maka nilai singularnya akan sama dengan eigenvalue-nya. Untuk matriks umum (tidak harus persegi atau simetris), nilai singular dan eigenvalue adalah konsep yang berbeda.

In [ ]:
#Bentuk SVD
import numpy as np

# Input
n = int(input("input dimensi matriks n: "))

# Input matriks A
A_list = []
for i in range(n):
    baris = list(map(float, input(f"input nilai elemen baris ke-{i+1}: ").split()))
    A_list.append(baris)
A = np.array(A_list)

# Hitung EVD (eigen values) sebagai pembanding
eigvals, eigvecs = np.linalg.eig(A)
print("\nEigenvalues:")
print(eigvals)

# Hitung SVD (singular values)
U, S, VT = np.linalg.svd(A)
print("\nSingular values:")
print(S)

input dimensi matriks n: 2
input nilai elemen baris ke-1: 1 2
input nilai elemen baris ke-2: 2 3

Eigenvalues:
[-0.23606798  4.23606798]

Singular values:
[4.23606798 0.23606798]


# Kesimpulan

* **Metode Power** dan **Metode QR** adalah metode langsung untuk mengaproksimasi atau menghitung eigenvalue.
* **Metode Householder's** adalah teknik reduksi matriks yang sering digunakan sebagai langkah awal dalam algoritma eigenvalue yang lebih canggih, terutama sebelum menerapkan metode QR.
* **SVD (Singular Value Decomposition)** memberikan nilai singular, yang berbeda dari eigenvalue kecuali untuk kasus matriks simetris positif-definit. Jadi, SVD tidak secara umum dianggap sebagai teknik aproksimasi eigenvalue.

Oleh karena itu, dari daftar yang Anda berikan, **Metode Power** dan **Metode QR** adalah teknik utama untuk aproksimasi eigenvalue. Metode Householder's berperan penting dalam mempermudah perhitungan eigenvalue, terutama dalam konteks metode QR. SVD memberikan informasi yang berbeda (nilai singular).

PERBEDAAN QR SHIFT

In [ ]:
import numpy as np

def qr_iteration(A, max_iter=100, tol=1e-10, use_shift=False):
    n = A.shape[0]
    Ak = A.copy()
    print("mu",Ak[-1,-1])
    for k in range(max_iter):
        if use_shift:
            # Shift: gunakan elemen terakhir diagonal sebagai mu
            mu = Ak[-1, -1]
            # print("mu :",mu)
            Q, R = np.linalg.qr(Ak - mu * np.eye(n))
            Ak = R @ Q + mu * np.eye(n)
        else:
            Q, R = np.linalg.qr(Ak)
            Ak = R @ Q

        # Cek konvergensi (lihat nilai sub-diagonal mengecil)
        off_diagonal_norm = np.sqrt(np.sum(np.tril(Ak, -1)**2))
        if off_diagonal_norm < tol:
            break
    return np.diag(Ak), k + 1  # k+1 iterasi dilakukan

# Contoh matriks
A = np.array([[4.0, 1.0, -2.0, 2.0],
              [1.0, 2.0, 0.0, 1.0],
              [-2.0, 0.0, 3.0, -2.0],
              [2.0, 1.0, -2.0, -1.0]])

eigen_no_shift, iter_no_shift = qr_iteration(A, use_shift=False)
eigen_with_shift, iter_with_shift = qr_iteration(A, use_shift=True)

print("Metode QR tanpa shift:")
print("Eigenvalue:", eigen_no_shift)
print("Jumlah iterasi:", iter_no_shift)

print("\nMetode QR dengan shift:")
print("Eigenvalue:", eigen_with_shift)
print("Jumlah iterasi:", iter_with_shift)


mu -1.0
mu -1.0
Metode QR tanpa shift:
Eigenvalue: [ 6.84462111  2.2683083  -2.19729387  1.08436446]
Jumlah iterasi: 100

Metode QR dengan shift:
Eigenvalue: [ 6.84462111  2.26853141  1.08436446 -2.19751698]
Jumlah iterasi: 75
